#!/bin/sh

request() {
    method=${1}
    url=${2}
    expected_http_status=${3}
    parameters=${4}
    if [ -z "${parameters}" ]
    then
        echo "curl -X ${method} -o /dev/null -s -w "%{http_code}\n" --header 'Accept: application/json' ${url}"
        http_status=`curl -X ${method} -o /dev/null -s -w "%{http_code}\n" --header 'Accept: application/json' ${url}`
    else
        echo "curl -X ${method} -d ${parameters} -o /dev/null -s -w "%{http_code}\n" --header 'Accept: application/json' ${url}"
        http_status=`curl -X ${method} -d ${parameters} -o /dev/null -s -w "%{http_code}\n" --header 'Accept: application/json' ${url}`
    fi
    if [ ${http_status} != ${expected_http_status} ]
    then
        echo "${method} ${url} ${parameters} ${http_status} while expecting ${expected_http_status}"
        exit 1
    fi
}

get() {
    request GET ${1} ${2} ${3}
}

post() {
    request POST ${1} ${2} "${3}"
}

put() {
    request PUT ${1} ${2} ${3}
}

delete() {
    request DELETE ${1} ${2} ${3}
}

get http://localhost:3000/users 200 # return default user
get http://localhost:3000/users/0 200 # return default user via id research
get http://localhost:3000/users/1 404 # http not found exception because user 1 does not exist
post http://localhost:3000/users 201 "firstname=Jane&lastname=Doe&age=23" # create user 1 : Jane Doe 23
get http://localhost:3000/users/1 200 # return user 1
put http://localhost:3000/users/1 200 "firstname=Janette&lastname=Doe&age=32" # modify user 1 in Janette Doe 32
delete http://localhost:3000/users/1 200 # delete user 1
get http://localhost:3000/users/1 404 # http not found exception because user 1 does not exist anymore

get http://localhost:3000/associations 200 # return default association
get http://localhost:3000/associations/0 200 # return default association
get http://localhost:3000/associations/1 404 # http not found exception because association 1 does not exist
post http://localhost:3000/associations 201 "idUsers[]=1&name=Assoc1" # create association 1 named Assoc1
get http://localhost:3000/associations/1 200 # return association 1 : Assoc1
post http://localhost:3000/users 201 "firstname=Jane&lastname=Doe&age=23" # create user 1 : Jane Doe
put http://localhost:3000/associations/1 200 "idUsers[]=1&idUsers[]=2&name=Assoc1"
delete http://localhost:3000/associations/1 200
get http://localhost:3000/associations/1 404
get http://localhost:3000/associations/0/members 200
